server:
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads
spring:
  datasource:
    url: jdbc:oracle:thin:@47.104.80.42:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: cloud1
    password: root
    
  redis:
    host: techhero-redis
    port: 6379
    password: 
    timeout: 10000
    lettuce:
      pool:
        max-idle: 4
        min-idle: 1
        max-active: 5
        max-wait: 10000
  rabbitmq:
    host: techhero-rabbitmq
    port: 5672
    username: guest
    password: guest
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
redis:
  cache:
    expiration: 3601
ribbon:
  eager-load:
    enabled: true
    clients: techhero-auth,techhero-user-service
  Httpclient:
    enabled: true
  OkHttp:
    enabled: false
  ReadTimeout: 10000
  ConnectTimeout: 10000
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: false
  httpclient:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#关闭验证
management:
  metrics:
    web:
      server:
        auto-time-requests: false
